#include "WinBase.h" // for IsBadReadPtr on windows only

#include <Geode/cocos/include/cocos2d.h>
#include <Geode/Geode.hpp>

#include <Geode/binding/AdvancedFollowInstance.hpp>
#include <Geode/binding/SFXTriggerInstance.hpp>
#include <Geode/binding/EventTriggerInstance.hpp>
#include <Geode/binding/SongChannelState.hpp>
#include <Geode/binding/SongTriggerState.hpp>
#include <Geode/binding/SFXStateContainer.hpp>
#include <Geode/binding/SFXTriggerState.hpp>
#include <Geode/binding/ChanceObject.hpp>
#include <Geode/binding/SmartPrefabResult.hpp>
#include <Geode/binding/GameObjectPhysics.hpp>
#include <Geode/binding/DynamicObjectAction.hpp>
#include <Geode/binding/GJTransformState.hpp>
#include <Geode/binding/CAState.hpp>
#include <Geode/binding/GJPointDouble.hpp>
#include <Geode/binding/SavedObjectStateRef.hpp>
#include <Geode/binding/SavedActiveObjectState.hpp>
#include <Geode/binding/SavedSpecialObjectState.hpp>
#include <Geode/binding/SequenceTriggerState.hpp>
#include <Geode/binding/SoundStateContainer.hpp>
#include <Geode/binding/TimerItem.hpp>
#include <Geode/binding/EnterEffectAnimValue.hpp>
#include <Geode/binding/DynamicMoveCalculation.hpp>
#include <Geode/binding/tk_spline.hpp>
#include <Geode/binding/RecordCheckpoint.hpp>
#include <Geode/binding/RecordButtonCommand.hpp>
#include <Geode/binding/GJDropDownLayer.hpp>
#include <Geode/binding/GJAccountDelegate.hpp>
#include <Geode/binding/FLAlertLayerProtocol.hpp>
#include <Geode/binding/AccountHelpLayer.hpp>
#include <Geode/binding/GJAccountBackupDelegate.hpp>
#include <Geode/binding/GJAccountSyncDelegate.hpp>
#include <Geode/binding/AccountLayer.hpp>
#include <Geode/binding/FLAlertLayer.hpp>
#include <Geode/binding/TextInputDelegate.hpp>
#include <Geode/binding/GJAccountLoginDelegate.hpp>
#include <Geode/binding/AccountLoginLayer.hpp>
#include <Geode/binding/GJAccountRegisterDelegate.hpp>
#include <Geode/binding/AccountRegisterLayer.hpp>
#include <Geode/binding/AchievementBar.hpp>
#include <Geode/binding/CCIndexPath.hpp>
#include <Geode/binding/TableViewCell.hpp>
#include <Geode/binding/AchievementCell.hpp>
#include <Geode/binding/AchievementManager.hpp>
#include <Geode/binding/AchievementNotifier.hpp>
#include <Geode/binding/AchievementsLayer.hpp>
#include <Geode/binding/AdToolbox.hpp>
#include <Geode/binding/CCSpritePlus.hpp>
#include <Geode/binding/GameObject.hpp>
#include <Geode/binding/EnhancedGameObject.hpp>
#include <Geode/binding/EffectGameObject.hpp>
#include <Geode/binding/AdvancedFollowTriggerObject.hpp>
#include <Geode/binding/AdvancedFollowEditObject.hpp>
#include <Geode/binding/AdvFollowSetup.hpp>
#include <Geode/binding/AnimatedSpriteDelegate.hpp>
#include <Geode/binding/SpritePartDelegate.hpp>
#include <Geode/binding/AnimatedGameObject.hpp>
#include <Geode/binding/CCAnimatedSprite.hpp>
#include <Geode/binding/AnimatedShopKeeper.hpp>
#include <Geode/binding/AppDelegate.hpp>
#include <Geode/binding/ArtistCell.hpp>
#include <Geode/binding/ArtTriggerGameObject.hpp>
#include <Geode/binding/TableViewCellDelegate.hpp>
#include <Geode/binding/MusicDownloadDelegate.hpp>
#include <Geode/binding/AudioAssetsBrowser.hpp>
#include <Geode/binding/AudioEffectsLayer.hpp>
#include <Geode/binding/AudioLineGuideGameObject.hpp>
#include <Geode/binding/BitmapFontCache.hpp>
#include <Geode/binding/BonusDropdown.hpp>
#include <Geode/binding/BoomListLayer.hpp>
#include <Geode/binding/TableViewDelegate.hpp>
#include <Geode/binding/TableViewDataSource.hpp>
#include <Geode/binding/BoomListView.hpp>
#include <Geode/binding/BoomScrollLayer.hpp>
#include <Geode/binding/BoomScrollLayerDelegate.hpp>
#include <Geode/binding/BrowseSmartTemplateLayer.hpp>
#include <Geode/binding/BrowseSmartKeyLayer.hpp>
#include <Geode/binding/ButtonPage.hpp>
#include <Geode/binding/ButtonSprite.hpp>
#include <Geode/binding/CameraTriggerGameObject.hpp>
#include <Geode/binding/CCAlertCircle.hpp>
#include <Geode/binding/CCAnimateFrameCache.hpp>
#include <Geode/binding/CCBlockLayer.hpp>
#include <Geode/binding/CCCircleWave.hpp>
#include <Geode/binding/CCCircleAlert.hpp>
#include <Geode/binding/CCCircleWaveDelegate.hpp>
#include <Geode/binding/CCContentLayer.hpp>
#include <Geode/binding/CCCountdown.hpp>
#include <Geode/binding/CCCounterLabel.hpp>
#include <Geode/binding/CCExtenderNode.hpp>
#include <Geode/binding/CCLightFlash.hpp>
#include <Geode/binding/CCLightStrip.hpp>
#include <Geode/binding/CCMenuItemSpriteExtra.hpp>
#include <Geode/binding/CCMenuItemToggler.hpp>
#include <Geode/binding/CCMoveCNode.hpp>
#include <Geode/binding/CCNodeContainer.hpp>
#include <Geode/binding/CCPartAnimSprite.hpp>
#include <Geode/binding/CCScrollLayerExt.hpp>
#include <Geode/binding/CCScrollLayerExtDelegate.hpp>
#include <Geode/binding/CCSpriteCOpacity.hpp>
#include <Geode/binding/CCSpriteWithHue.hpp>
#include <Geode/binding/CCSpriteGrayscale.hpp>
#include <Geode/binding/CCSpritePart.hpp>
#include <Geode/binding/CCTextInputNode.hpp>
#include <Geode/binding/CCURLObject.hpp>
#include <Geode/binding/GJChallengeDelegate.hpp>
#include <Geode/binding/CurrencyRewardDelegate.hpp>
#include <Geode/binding/ChallengesPage.hpp>
#include <Geode/binding/GJChallengeItem.hpp>
#include <Geode/binding/ChallengeNode.hpp>
#include <Geode/binding/ChanceTriggerGameObject.hpp>
#include <Geode/binding/CharacterColorDelegate.hpp>
#include <Geode/binding/CharacterColorPage.hpp>
#include <Geode/binding/CheckpointGameObject.hpp>
#include <Geode/binding/EnterEffectInstance.hpp>
#include <Geode/binding/GJValueTween.hpp>
#include <Geode/binding/GJGameState.hpp>
#include <Geode/binding/GJShaderState.hpp>
#include <Geode/binding/PulseEffectAction.hpp>
#include <Geode/binding/CountTriggerAction.hpp>
#include <Geode/binding/OpacityEffectAction.hpp>
#include <Geode/binding/TouchToggleAction.hpp>
#include <Geode/binding/CollisionTriggerAction.hpp>
#include <Geode/binding/ToggleTriggerAction.hpp>
#include <Geode/binding/SpawnTriggerAction.hpp>
#include <Geode/binding/KeyframeObject.hpp>
#include <Geode/binding/GroupCommandObject2.hpp>
#include <Geode/binding/TimerTriggerAction.hpp>
#include <Geode/binding/EffectManagerState.hpp>
#include <Geode/binding/CheckpointObject.hpp>
#include <Geode/binding/CollisionBlockPopup.hpp>
#include <Geode/binding/ColorAction.hpp>
#include <Geode/binding/ColorAction2.hpp>
#include <Geode/binding/ColorActionSprite.hpp>
#include <Geode/binding/ColorChannelSprite.hpp>
#include <Geode/binding/ColorSelectDelegate.hpp>
#include <Geode/binding/ColorSelectLiveOverlay.hpp>
#include <Geode/binding/ConfigureValuePopupDelegate.hpp>
#include <Geode/binding/SliderDelegate.hpp>
#include <Geode/binding/SetupTriggerPopup.hpp>
#include <Geode/binding/GJSpecialColorSelectDelegate.hpp>
#include <Geode/binding/ColorSelectPopup.hpp>
#include <Geode/binding/ColorSetupDelegate.hpp>
#include <Geode/binding/LikeItemDelegate.hpp>
#include <Geode/binding/CommentCell.hpp>
#include <Geode/binding/CommentUploadDelegate.hpp>
#include <Geode/binding/CommunityCreditNode.hpp>
#include <Geode/binding/CommunityCreditsPage.hpp>
#include <Geode/binding/ConfigureHSVWidget.hpp>
#include <Geode/binding/ConfigureValuePopup.hpp>
#include <Geode/binding/CountTriggerGameObject.hpp>
#include <Geode/binding/CreateGuidelinesLayer.hpp>
#include <Geode/binding/CreateMenuItem.hpp>
#include <Geode/binding/CreateParticlePopup.hpp>
#include <Geode/binding/DialogDelegate.hpp>
#include <Geode/binding/CreatorLayer.hpp>
#include <Geode/binding/CurrencyRewardLayer.hpp>
#include <Geode/binding/CurrencySprite.hpp>
#include <Geode/binding/HSVWidgetDelegate.hpp>
#include <Geode/binding/CustomizeObjectLayer.hpp>
#include <Geode/binding/CustomizeObjectSettingsPopup.hpp>
#include <Geode/binding/CustomListView.hpp>
#include <Geode/binding/CustomSongDelegate.hpp>
#include <Geode/binding/CustomSongCell.hpp>
#include <Geode/binding/CustomMusicCell.hpp>
#include <Geode/binding/CustomSFXDelegate.hpp>
#include <Geode/binding/CustomSFXCell.hpp>
#include <Geode/binding/CustomSFXWidget.hpp>
#include <Geode/binding/GJDropDownLayerDelegate.hpp>
#include <Geode/binding/MusicBrowserDelegate.hpp>
#include <Geode/binding/CustomSongLayer.hpp>
#include <Geode/binding/CustomSongLayerDelegate.hpp>
#include <Geode/binding/GJAssetDownloadAction.hpp>
#include <Geode/binding/CustomSongWidget.hpp>
#include <Geode/binding/DailyLevelNode.hpp>
#include <Geode/binding/GJDailyLevelDelegate.hpp>
#include <Geode/binding/LevelDownloadDelegate.hpp>
#include <Geode/binding/DailyLevelPage.hpp>
#include <Geode/binding/RingObject.hpp>
#include <Geode/binding/DashRingObject.hpp>
#include <Geode/binding/DelayedSpawnNode.hpp>
#include <Geode/binding/DemonFilterDelegate.hpp>
#include <Geode/binding/DemonFilterSelectLayer.hpp>
#include <Geode/binding/DemonInfoPopup.hpp>
#include <Geode/binding/TextAreaDelegate.hpp>
#include <Geode/binding/DialogLayer.hpp>
#include <Geode/binding/DialogObject.hpp>
#include <Geode/binding/DownloadMessageDelegate.hpp>
#include <Geode/binding/DrawGridLayer.hpp>
#include <Geode/binding/DungeonBarsSprite.hpp>
#include <Geode/binding/DynamicBitset.hpp>
#include <Geode/binding/DynamicScrollDelegate.hpp>
#include <Geode/binding/EditButtonBar.hpp>
#include <Geode/binding/EditGameObjectPopup.hpp>
#include <Geode/binding/UploadActionDelegate.hpp>
#include <Geode/binding/UploadPopupDelegate.hpp>
#include <Geode/binding/SetIDPopupDelegate.hpp>
#include <Geode/binding/EditLevelLayer.hpp>
#include <Geode/binding/GJOptionsLayer.hpp>
#include <Geode/binding/EditorOptionsLayer.hpp>
#include <Geode/binding/EditorPauseLayer.hpp>
#include <Geode/binding/GameObjectEditorState.hpp>
#include <Geode/binding/GJRotationControlDelegate.hpp>
#include <Geode/binding/GJScaleControlDelegate.hpp>
#include <Geode/binding/GJTransformControlDelegate.hpp>
#include <Geode/binding/EditorUI.hpp>
#include <Geode/binding/EditTriggersPopup.hpp>
#include <Geode/binding/EndLevelLayer.hpp>
#include <Geode/binding/EndPortalObject.hpp>
#include <Geode/binding/EndTriggerGameObject.hpp>
#include <Geode/binding/EnhancedTriggerObject.hpp>
#include <Geode/binding/EnterEffectObject.hpp>
#include <Geode/binding/EventLinkTrigger.hpp>
#include <Geode/binding/ExplodeItemNode.hpp>
#include <Geode/binding/ExplodeItemSprite.hpp>
#include <Geode/binding/ExtendedLayer.hpp>
#include <Geode/binding/FileOperation.hpp>
#include <Geode/binding/GManager.hpp>
#include <Geode/binding/FileSaveManager.hpp>
#include <Geode/binding/FindBPMLayer.hpp>
#include <Geode/binding/SetIDPopup.hpp>
#include <Geode/binding/FindObjectPopup.hpp>
#include <Geode/binding/GameRateDelegate.hpp>
#include <Geode/binding/RewardedVideoDelegate.hpp>
#include <Geode/binding/FollowRewardPage.hpp>
#include <Geode/binding/FontObject.hpp>
#include <Geode/binding/ForceBlockGameObject.hpp>
#include <Geode/binding/FriendRequestDelegate.hpp>
#include <Geode/binding/FRequestProfilePage.hpp>
#include <Geode/binding/FriendRequestPopup.hpp>
#include <Geode/binding/UserListDelegate.hpp>
#include <Geode/binding/FriendsProfilePage.hpp>
#include <Geode/binding/GameCell.hpp>
#include <Geode/binding/GameEffectsManager.hpp>
#include <Geode/binding/GameLevelManager.hpp>
#include <Geode/binding/GameLevelOptionsLayer.hpp>
#include <Geode/binding/UIButtonConfig.hpp>
#include <Geode/binding/GameManager.hpp>
#include <Geode/binding/GameObjectCopy.hpp>
#include <Geode/binding/GameOptionsLayer.hpp>
#include <Geode/binding/GameOptionsTrigger.hpp>
#include <Geode/binding/GameStatsManager.hpp>
#include <Geode/binding/GameToolbox.hpp>
#include <Geode/binding/LevelManagerDelegate.hpp>
#include <Geode/binding/GauntletLayer.hpp>
#include <Geode/binding/GauntletNode.hpp>
#include <Geode/binding/GauntletSelectLayer.hpp>
#include <Geode/binding/GauntletSprite.hpp>
#include <Geode/binding/GhostTrailEffect.hpp>
#include <Geode/binding/GJAccountManager.hpp>
#include <Geode/binding/GJAccountSettingsDelegate.hpp>
#include <Geode/binding/GJAccountSettingsLayer.hpp>
#include <Geode/binding/GJActionManager.hpp>
#include <Geode/binding/PlayerButtonCommand.hpp>
#include <Geode/binding/TriggerEffectDelegate.hpp>
#include <Geode/binding/GJBaseGameLayer.hpp>
#include <Geode/binding/GJBigSprite.hpp>
#include <Geode/binding/GJBigSpriteNode.hpp>
#include <Geode/binding/GJChestSprite.hpp>
#include <Geode/binding/GJColorSetupLayer.hpp>
#include <Geode/binding/GJComment.hpp>
#include <Geode/binding/GJCommentListLayer.hpp>
#include <Geode/binding/GJDifficultySprite.hpp>
#include <Geode/binding/GJEffectManager.hpp>
#include <Geode/binding/GJGroundLayer.hpp>
#include <Geode/binding/GJFlyGroundLayer.hpp>
#include <Geode/binding/GJFollowCommandLayer.hpp>
#include <Geode/binding/GJFriendRequest.hpp>
#include <Geode/binding/GJGameLevel.hpp>
#include <Geode/binding/GJGameLoadingLayer.hpp>
#include <Geode/binding/ListButtonBarDelegate.hpp>
#include <Geode/binding/GJGarageLayer.hpp>
#include <Geode/binding/GJGradientLayer.hpp>
#include <Geode/binding/GJHttpResult.hpp>
#include <Geode/binding/GJItemIcon.hpp>
#include <Geode/binding/GJLevelList.hpp>
#include <Geode/binding/GJLevelScoreCell.hpp>
#include <Geode/binding/GJListLayer.hpp>
#include <Geode/binding/GJLocalLevelScoreCell.hpp>
#include <Geode/binding/GJLocalScore.hpp>
#include <Geode/binding/GJMapObject.hpp>
#include <Geode/binding/GJMapPack.hpp>
#include <Geode/binding/GJMessageCell.hpp>
#include <Geode/binding/GJMessagePopup.hpp>
#include <Geode/binding/GJMGLayer.hpp>
#include <Geode/binding/GJMoreGamesLayer.hpp>
#include <Geode/binding/GJMPDelegate.hpp>
#include <Geode/binding/GJMultiplayerManager.hpp>
#include <Geode/binding/GJObjectDecoder.hpp>
#include <Geode/binding/GJOnlineRewardDelegate.hpp>
#include <Geode/binding/GJPurchaseDelegate.hpp>
#include <Geode/binding/GJPathPage.hpp>
#include <Geode/binding/GJPathRewardPopup.hpp>
#include <Geode/binding/GJPathsLayer.hpp>
#include <Geode/binding/GJPathSprite.hpp>
#include <Geode/binding/GJPFollowCommandLayer.hpp>
#include <Geode/binding/GJPromoPopup.hpp>
#include <Geode/binding/LevelRateInfoDelegate.hpp>
#include <Geode/binding/GJRateLevelLayer.hpp>
#include <Geode/binding/GJRequestCell.hpp>
#include <Geode/binding/GJRewardDelegate.hpp>
#include <Geode/binding/GJRewardItem.hpp>
#include <Geode/binding/GJRewardObject.hpp>
#include <Geode/binding/GJRobotSprite.hpp>
#include <Geode/binding/GJRotateCommandLayer.hpp>
#include <Geode/binding/GJRotationControl.hpp>
#include <Geode/binding/GJScaleControl.hpp>
#include <Geode/binding/GJScoreCell.hpp>
#include <Geode/binding/GJSearchObject.hpp>
#include <Geode/binding/GJShopLayer.hpp>
#include <Geode/binding/GJSmartBlockPreview.hpp>
#include <Geode/binding/GJSmartBlockPreviewSprite.hpp>
#include <Geode/binding/GJSmartPrefab.hpp>
#include <Geode/binding/GJSmartTemplate.hpp>
#include <Geode/binding/GJSongBrowser.hpp>
#include <Geode/binding/GJSpecialColorSelect.hpp>
#include <Geode/binding/GJSpiderSprite.hpp>
#include <Geode/binding/GJSpriteColor.hpp>
#include <Geode/binding/GJStoreItem.hpp>
#include <Geode/binding/GJTransformControl.hpp>
#include <Geode/binding/GJUINode.hpp>
#include <Geode/binding/GJUnlockableItem.hpp>
#include <Geode/binding/GJUserCell.hpp>
#include <Geode/binding/GJUserMessage.hpp>
#include <Geode/binding/GJUserScore.hpp>
#include <Geode/binding/GJWorldNode.hpp>
#include <Geode/binding/UploadMessageDelegate.hpp>
#include <Geode/binding/GJWriteMessagePopup.hpp>
#include <Geode/binding/GooglePlayDelegate.hpp>
#include <Geode/binding/GooglePlayManager.hpp>
#include <Geode/binding/GradientTriggerObject.hpp>
#include <Geode/binding/GraphicsReloadLayer.hpp>
#include <Geode/binding/GravityEffectSprite.hpp>
#include <Geode/binding/HardStreak.hpp>
#include <Geode/binding/HSVLiveOverlay.hpp>
#include <Geode/binding/HSVWidgetPopup.hpp>
#include <Geode/binding/InfoAlertButton.hpp>
#include <Geode/binding/LevelCommentDelegate.hpp>
#include <Geode/binding/InfoLayer.hpp>
#include <Geode/binding/InheritanceNode.hpp>
#include <Geode/binding/ItemInfoPopup.hpp>
#include <Geode/binding/ItemTriggerGameObject.hpp>
#include <Geode/binding/KeybindingsLayer.hpp>
#include <Geode/binding/KeybindingsManager.hpp>
#include <Geode/binding/KeyframeAnimTriggerObject.hpp>
#include <Geode/binding/KeyframeGameObject.hpp>
#include <Geode/binding/LabelGameObject.hpp>
#include <Geode/binding/LeaderboardManagerDelegate.hpp>
#include <Geode/binding/LeaderboardsLayer.hpp>
#include <Geode/binding/LevelAreaInnerLayer.hpp>
#include <Geode/binding/LevelAreaLayer.hpp>
#include <Geode/binding/SetTextPopupDelegate.hpp>
#include <Geode/binding/ShareCommentDelegate.hpp>
#include <Geode/binding/LevelBrowserLayer.hpp>
#include <Geode/binding/LevelCell.hpp>
#include <Geode/binding/LevelDeleteDelegate.hpp>
#include <Geode/binding/LevelSettingsDelegate.hpp>
#include <Geode/binding/LevelEditorLayer.hpp>
#include <Geode/binding/LevelFeatureLayer.hpp>
#include <Geode/binding/LevelUpdateDelegate.hpp>
#include <Geode/binding/RateLevelDelegate.hpp>
#include <Geode/binding/NumberInputDelegate.hpp>
#include <Geode/binding/LevelInfoLayer.hpp>
#include <Geode/binding/LevelLeaderboard.hpp>
#include <Geode/binding/LevelListCell.hpp>
#include <Geode/binding/LevelListDeleteDelegate.hpp>
#include <Geode/binding/SelectListIconDelegate.hpp>
#include <Geode/binding/LevelListLayer.hpp>
#include <Geode/binding/LevelOptionsLayer.hpp>
#include <Geode/binding/LevelOptionsLayer2.hpp>
#include <Geode/binding/LevelPage.hpp>
#include <Geode/binding/LevelSearchLayer.hpp>
#include <Geode/binding/LevelSelectLayer.hpp>
#include <Geode/binding/SelectArtDelegate.hpp>
#include <Geode/binding/SelectSettingDelegate.hpp>
#include <Geode/binding/LevelSettingsLayer.hpp>
#include <Geode/binding/LevelSettingsObject.hpp>
#include <Geode/binding/LevelTools.hpp>
#include <Geode/binding/LevelUploadDelegate.hpp>
#include <Geode/binding/LikeItemLayer.hpp>
#include <Geode/binding/ListButtonBar.hpp>
#include <Geode/binding/ListButtonPage.hpp>
#include <Geode/binding/ListCell.hpp>
#include <Geode/binding/ListUploadDelegate.hpp>
#include <Geode/binding/LoadingCircle.hpp>
#include <Geode/binding/LoadingCircleSprite.hpp>
#include <Geode/binding/LoadingLayer.hpp>
#include <Geode/binding/LocalLevelManager.hpp>
#include <Geode/binding/MapPackCell.hpp>
#include <Geode/binding/MapSelectLayer.hpp>
#include <Geode/binding/MenuGameLayer.hpp>
#include <Geode/binding/MenuLayer.hpp>
#include <Geode/binding/MessageListDelegate.hpp>
#include <Geode/binding/MessagesProfilePage.hpp>
#include <Geode/binding/MoreOptionsLayer.hpp>
#include <Geode/binding/MoreSearchLayer.hpp>
#include <Geode/binding/MoreVideoOptionsLayer.hpp>
#include <Geode/binding/MPLobbyLayer.hpp>
#include <Geode/binding/MultilineBitmapFont.hpp>
#include <Geode/binding/MultiplayerLayer.hpp>
#include <Geode/binding/MultiTriggerPopup.hpp>
#include <Geode/binding/MusicArtistObject.hpp>
#include <Geode/binding/MusicBrowser.hpp>
#include <Geode/binding/MusicDelegateHandler.hpp>
#include <Geode/binding/PlatformDownloadDelegate.hpp>
#include <Geode/binding/MusicDownloadManager.hpp>
#include <Geode/binding/OptionsObjectDelegate.hpp>
#include <Geode/binding/MusicSearchResult.hpp>
#include <Geode/binding/NCSInfoLayer.hpp>
#include <Geode/binding/NewgroundsInfoLayer.hpp>
#include <Geode/binding/NodePoint.hpp>
#include <Geode/binding/NumberInputLayer.hpp>
#include <Geode/binding/OBB2D.hpp>
#include <Geode/binding/ObjectControlGameObject.hpp>
#include <Geode/binding/ObjectManager.hpp>
#include <Geode/binding/ObjectToolbox.hpp>
#include <Geode/binding/OnlineListDelegate.hpp>
#include <Geode/binding/OptionsCell.hpp>
#include <Geode/binding/OptionsLayer.hpp>
#include <Geode/binding/OptionsObject.hpp>
#include <Geode/binding/OptionsScrollLayer.hpp>
#include <Geode/binding/ParentalOptionsLayer.hpp>
#include <Geode/binding/ParticleGameObject.hpp>
#include <Geode/binding/ParticlePreviewLayer.hpp>
#include <Geode/binding/PauseLayer.hpp>
#include <Geode/binding/PlatformToolbox.hpp>
#include <Geode/binding/PlayerCheckpoint.hpp>
#include <Geode/binding/PlayerControlGameObject.hpp>
#include <Geode/binding/PlayerFireBoostSprite.hpp>
#include <Geode/binding/PlayerObject.hpp>
#include <Geode/binding/PlayLayer.hpp>
#include <Geode/binding/PointNode.hpp>
#include <Geode/binding/PriceLabel.hpp>
#include <Geode/binding/UserInfoDelegate.hpp>
#include <Geode/binding/ProfilePage.hpp>
#include <Geode/binding/PromoInterstitial.hpp>
#include <Geode/binding/PurchaseItemPopup.hpp>
#include <Geode/binding/RandTriggerGameObject.hpp>
#include <Geode/binding/RateDemonLayer.hpp>
#include <Geode/binding/RateLevelLayer.hpp>
#include <Geode/binding/RateStarsLayer.hpp>
#include <Geode/binding/RetryLevelLayer.hpp>
#include <Geode/binding/RewardsPage.hpp>
#include <Geode/binding/RewardUnlockLayer.hpp>
#include <Geode/binding/RotateGameplayGameObject.hpp>
#include <Geode/binding/ScrollingLayer.hpp>
#include <Geode/binding/SearchButton.hpp>
#include <Geode/binding/SetTextPopup.hpp>
#include <Geode/binding/SearchSFXPopup.hpp>
#include <Geode/binding/SecretGame01Layer.hpp>
#include <Geode/binding/SecretLayer.hpp>
#include <Geode/binding/SecretLayer2.hpp>
#include <Geode/binding/SecretLayer3.hpp>
#include <Geode/binding/SecretLayer4.hpp>
#include <Geode/binding/SecretLayer5.hpp>
#include <Geode/binding/SecretLayer6.hpp>
#include <Geode/binding/SecretNumberLayer.hpp>
#include <Geode/binding/SecretRewardsLayer.hpp>
#include <Geode/binding/SelectArtLayer.hpp>
#include <Geode/binding/SelectEventLayer.hpp>
#include <Geode/binding/SelectFontLayer.hpp>
#include <Geode/binding/SelectListIconLayer.hpp>
#include <Geode/binding/SelectPremadeDelegate.hpp>
#include <Geode/binding/SelectPremadeLayer.hpp>
#include <Geode/binding/SelectSettingLayer.hpp>
#include <Geode/binding/SelectSFXSortDelegate.hpp>
#include <Geode/binding/SelectSFXSortLayer.hpp>
#include <Geode/binding/SequenceTriggerGameObject.hpp>
#include <Geode/binding/SetColorIDPopup.hpp>
#include <Geode/binding/SetFolderPopup.hpp>
#include <Geode/binding/SetGroupIDLayer.hpp>
#include <Geode/binding/SetItemIDLayer.hpp>
#include <Geode/binding/SetLevelOrderPopup.hpp>
#include <Geode/binding/SetTargetIDLayer.hpp>
#include <Geode/binding/SetupAdvFollowEditPhysicsPopup.hpp>
#include <Geode/binding/SetupAdvFollowPopup.hpp>
#include <Geode/binding/SetupAdvFollowRetargetPopup.hpp>
#include <Geode/binding/SetupAnimationPopup.hpp>
#include <Geode/binding/SetupAnimSettingsPopup.hpp>
#include <Geode/binding/SetupAreaMoveTriggerPopup.hpp>
#include <Geode/binding/SetupAreaTintTriggerPopup.hpp>
#include <Geode/binding/SetupAreaAnimTriggerPopup.hpp>
#include <Geode/binding/SetupAreaFadeTriggerPopup.hpp>
#include <Geode/binding/SetupAreaRotateTriggerPopup.hpp>
#include <Geode/binding/SetupAreaTransformTriggerPopup.hpp>
#include <Geode/binding/SetupAreaTriggerPopup.hpp>
#include <Geode/binding/SetupArtSwitchPopup.hpp>
#include <Geode/binding/SetupAudioLineGuidePopup.hpp>
#include <Geode/binding/SetupAudioTriggerPopup.hpp>
#include <Geode/binding/SetupBGSpeedTrigger.hpp>
#include <Geode/binding/SetupCameraEdgePopup.hpp>
#include <Geode/binding/SetupCameraGuidePopup.hpp>
#include <Geode/binding/SetupCameraModePopup.hpp>
#include <Geode/binding/SetupCameraOffsetTrigger.hpp>
#include <Geode/binding/SetupCameraRotatePopup.hpp>
#include <Geode/binding/SetupCameraRotatePopup2.hpp>
#include <Geode/binding/SetupCheckpointPopup.hpp>
#include <Geode/binding/SetupCoinLayer.hpp>
#include <Geode/binding/SetupInstantCollisionTriggerPopup.hpp>
#include <Geode/binding/SetupCollisionStateTriggerPopup.hpp>
#include <Geode/binding/SetupCollisionTriggerPopup.hpp>
#include <Geode/binding/SetupCountTriggerPopup.hpp>
#include <Geode/binding/SetupDashRingPopup.hpp>
#include <Geode/binding/SetupEndPopup.hpp>
#include <Geode/binding/SetupEnterEffectPopup.hpp>
#include <Geode/binding/SetupEnterTriggerPopup.hpp>
#include <Geode/binding/SetupEventLinkPopup.hpp>
#include <Geode/binding/SetupForceBlockPopup.hpp>
#include <Geode/binding/SetupGameplayOffsetPopup.hpp>
#include <Geode/binding/SetupGradientPopup.hpp>
#include <Geode/binding/SetupGravityModPopup.hpp>
#include <Geode/binding/SetupGravityTriggerPopup.hpp>
#include <Geode/binding/SetupInstantCountPopup.hpp>
#include <Geode/binding/SetupInteractObjectPopup.hpp>
#include <Geode/binding/SetupItemCompareTriggerPopup.hpp>
#include <Geode/binding/SetupItemEditTriggerPopup.hpp>
#include <Geode/binding/SetupKeyframeAnimPopup.hpp>
#include <Geode/binding/SetupKeyframePopup.hpp>
#include <Geode/binding/SetupMGTrigger.hpp>
#include <Geode/binding/SetupMoveCommandPopup.hpp>
#include <Geode/binding/SetupObjectControlPopup.hpp>
#include <Geode/binding/SetupObjectOptions2Popup.hpp>
#include <Geode/binding/SetupObjectOptionsPopup.hpp>
#include <Geode/binding/SetupObjectTogglePopup.hpp>
#include <Geode/binding/SetupOpacityPopup.hpp>
#include <Geode/binding/SetupOptionsTriggerPopup.hpp>
#include <Geode/binding/SetupPersistentItemTriggerPopup.hpp>
#include <Geode/binding/SetupPickupTriggerPopup.hpp>
#include <Geode/binding/SetupPlatformerEndPopup.hpp>
#include <Geode/binding/SetupPlayerControlPopup.hpp>
#include <Geode/binding/SetupPortalPopup.hpp>
#include <Geode/binding/SetupPulsePopup.hpp>
#include <Geode/binding/SetupRandAdvTriggerPopup.hpp>
#include <Geode/binding/SetupRandTriggerPopup.hpp>
#include <Geode/binding/SetupResetTriggerPopup.hpp>
#include <Geode/binding/SetupReverbPopup.hpp>
#include <Geode/binding/SetupRotateCommandPopup.hpp>
#include <Geode/binding/SetupRotateGameplayPopup.hpp>
#include <Geode/binding/SetupRotatePopup.hpp>
#include <Geode/binding/SetupSequenceTriggerPopup.hpp>
#include <Geode/binding/SetupSFXEditPopup.hpp>
#include <Geode/binding/SFXBrowserDelegate.hpp>
#include <Geode/binding/SetupSFXPopup.hpp>
#include <Geode/binding/SetupShaderEffectPopup.hpp>
#include <Geode/binding/SetupShakePopup.hpp>
#include <Geode/binding/SetupSmartBlockLayer.hpp>
#include <Geode/binding/SetupSmartTemplateLayer.hpp>
#include <Geode/binding/SongPlaybackDelegate.hpp>
#include <Geode/binding/SetupSongTriggerPopup.hpp>
#include <Geode/binding/SetupSpawnParticlePopup.hpp>
#include <Geode/binding/SetupSpawnPopup.hpp>
#include <Geode/binding/SetupStaticCameraPopup.hpp>
#include <Geode/binding/SetupStopTriggerPopup.hpp>
#include <Geode/binding/SetupTeleportPopup.hpp>
#include <Geode/binding/SetupTimerControlTriggerPopup.hpp>
#include <Geode/binding/SetupTimerEventTriggerPopup.hpp>
#include <Geode/binding/SetupTimerTriggerPopup.hpp>
#include <Geode/binding/SetupTimeWarpPopup.hpp>
#include <Geode/binding/SetupTouchTogglePopup.hpp>
#include <Geode/binding/SetupTransformPopup.hpp>
#include <Geode/binding/SetupZoomTriggerPopup.hpp>
#include <Geode/binding/SFXBrowser.hpp>
#include <Geode/binding/SFXInfoObject.hpp>
#include <Geode/binding/SFXFolderObject.hpp>
#include <Geode/binding/SFXSearchResult.hpp>
#include <Geode/binding/SFXTriggerGameObject.hpp>
#include <Geode/binding/ShaderGameObject.hpp>
#include <Geode/binding/ShaderLayer.hpp>
#include <Geode/binding/ShardsPage.hpp>
#include <Geode/binding/ShareCommentLayer.hpp>
#include <Geode/binding/ShareLevelLayer.hpp>
#include <Geode/binding/ShareLevelSettingsLayer.hpp>
#include <Geode/binding/ShareListLayer.hpp>
#include <Geode/binding/SimpleObject.hpp>
#include <Geode/binding/SimplePlayer.hpp>
#include <Geode/binding/SlideInLayer.hpp>
#include <Geode/binding/SliderThumb.hpp>
#include <Geode/binding/SliderTouchLogic.hpp>
#include <Geode/binding/Slider.hpp>
#include <Geode/binding/SmartGameObject.hpp>
#include <Geode/binding/SmartTemplateCell.hpp>
#include <Geode/binding/SongCell.hpp>
#include <Geode/binding/SongInfoLayer.hpp>
#include <Geode/binding/SongInfoObject.hpp>
#include <Geode/binding/SongObject.hpp>
#include <Geode/binding/SongOptionsLayer.hpp>
#include <Geode/binding/SongSelectNode.hpp>
#include <Geode/binding/SongsLayer.hpp>
#include <Geode/binding/SongTriggerGameObject.hpp>
#include <Geode/binding/SpawnParticleGameObject.hpp>
#include <Geode/binding/SpawnTriggerGameObject.hpp>
#include <Geode/binding/SpecialAnimGameObject.hpp>
#include <Geode/binding/SpriteAnimationManager.hpp>
#include <Geode/binding/SpriteDescription.hpp>
#include <Geode/binding/StarInfoPopup.hpp>
#include <Geode/binding/StartPosObject.hpp>
#include <Geode/binding/StatsCell.hpp>
#include <Geode/binding/StatsLayer.hpp>
#include <Geode/binding/StatsObject.hpp>
#include <Geode/binding/SupportLayer.hpp>
#include <Geode/binding/TableView.hpp>
#include <Geode/binding/TeleportPortalObject.hpp>
#include <Geode/binding/TextAlertPopup.hpp>
#include <Geode/binding/TextArea.hpp>
#include <Geode/binding/TextGameObject.hpp>
#include <Geode/binding/TextStyleSection.hpp>
#include <Geode/binding/TimerTriggerGameObject.hpp>
#include <Geode/binding/TopArtistsLayer.hpp>
#include <Geode/binding/TOSPopup.hpp>
#include <Geode/binding/TransformTriggerGameObject.hpp>
#include <Geode/binding/TriggerControlGameObject.hpp>
#include <Geode/binding/TutorialLayer.hpp>
#include <Geode/binding/TutorialPopup.hpp>
#include <Geode/binding/UILayer.hpp>
#include <Geode/binding/UIObjectSettingsPopup.hpp>
#include <Geode/binding/UIOptionsLayer.hpp>
#include <Geode/binding/UIPOptionsLayer.hpp>
#include <Geode/binding/UISaveLoadLayer.hpp>
#include <Geode/binding/UISettingsGameObject.hpp>
#include <Geode/binding/UndoObject.hpp>
#include <Geode/binding/UpdateAccountSettingsPopup.hpp>
#include <Geode/binding/UploadActionPopup.hpp>
#include <Geode/binding/UploadListPopup.hpp>
#include <Geode/binding/UploadPopup.hpp>
#include <Geode/binding/URLCell.hpp>
#include <Geode/binding/URLViewLayer.hpp>
#include <Geode/binding/VideoOptionsLayer.hpp>
#include <Geode/binding/WorldLevelPage.hpp>
#include <Geode/binding/WorldSelectLayer.hpp>

